### ISSUE TITLE
Release 추가 바랍니다.

### ISSUE THREAD

**Issue by mingkyme** [Howarf/RandomSkillDefence#1]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/45954551/171758119-21abad58-8c2e-4f19-ac78-ed2a2ed211ca.png">

apk 파일만 다운로드하면 된다고 적혀있네요

빌드해서 업로드해주시면 좋을 듯 합니다.
https://github.com/Howarf/RandomSkillDefence/releases

**Comment by Howarf** [comment]
이런거 처음이라 수정했습니다 감사합니다

**Comment by Howarf** [comment]
> 
이런거 처음이라 감사합니다 수정했습니다

**Comment by Howarf** [comment]
> <img alt="image" width="903" src="https://user-images.githubusercontent.com/45954551/171758119-21abad58-8c2e-4f19-ac78-ed2a2ed211ca.png">
> 
> apk 파일만 다운로드하면 된다고 적혀있네요
> 
> 빌드해서 업로드해주시면 좋을 듯 합니다. https://github.com/Howarf/RandomSkillDefence/releases

이런거 처음이라 수정했습니다 감사합니다

**Comment by mingkyme** [comment]
문제가 해결 됐으니 Issue는 close 하겠습니다.
